### ISSUE TITLE
Guix Package

### ISSUE THREAD

**Issue by wrest64** [ebeem/guile-swayer#1]
This looks great! Since this is most appealing to Guile folk, and many Guilers use Guix, it could be nice to have this set up as a Guix package.

[dwl-guile](https://github.com/engstrand-config/dwl-guile) is a similar project (dwl instead of sway), and they have set up a channel and Guix Home service.

**Comment by ebeem** [comment]
Thanks! I would love to make this happen. I am currently slowly switching to Guix.
I still have to study the way services are written, surely will add at least a package definition as soon as I am available.

PRs are very welcomed until then

**Comment by ispringle** [comment]
@wrest64 I'm new to Guile and Guix. I found your package (btw thanks!) but I'm totally clueless how to make use of it. I assumed that it'd just magically be in the guile load-path so I can just `(use-modules (swayipc))` but that's not the case. I looked and it's in the `.guix-profile/shares/guile/site/3.0/` dir. I was wondering if it should just be in there like that, it seems that it'd be sort of "polluting" that dir since it's not under a subdir ie `(use-modules (guile-swayer swayipc))`.

**Comment by ebeem** [comment]
@ispringle I agree, all of `libs`, `modules`, `sjson`, and `swayipc` in addition to the files `swayipc.scm` and `sjson.scm` should be under one directory, probably `src/guile-swayer`

This will break current configs though, since the module import will fail. It will also make it harder to just use the files as they are, one will have to install `guile-swayer` as a package rather than just place the files in their config directory.

However, I still think this is a change that must be done
Thanks for your suggestion

**Comment by ebeem** [comment]
@ispringle please check the PR #6 
It introduces a lot of changes, I will merge once tested

I will also create a new release so we can update the guix package definition

**Comment by ispringle** [comment]
Awesome, thanks for that effort!
